Repository pivotal-cf/docs-build-service, pull requests merged in 2020-06, with the labels that each got.

#59 Update installing docs for 0.2.0
  installing.html.md.erb
Labels: in progress

#60 Update Secrets in TBS Page for 0.2.0
  secrets-in-tbs.html.md.erb
Labels: in progress

#61 Update TBS without projects for 0.2.0
  tbs-without-projects.html.md.erb
Labels: in progress

#70 Update `Managing Secrets`
  managing-secrets.html.md.erb
Labels: scheduled

#62 Update faq docs for 0.2.0 release
  faq.html.md.erb
Labels: unscheduled

#64 Update accessing-tbs
  accessing-tbs.html.md.erb
Labels: unscheduled

#67 Update managing-builders docs
  managing-builders.html.md.erb
Labels: unscheduled

#71 Update managing images and builds docs
  managing-images.html.md.erb
Labels: unscheduled

#63 Update updating-deps
  updating-deps.html.md.erb
Labels: unscheduled

#65 Update managing-stack
  index.html.md.erb
  managing-stack.html.md.erb
  managing-stacks.html.md.erb
  using.html.md.erb
Labels: unscheduled

#66 Update managing-store
  index.html.md.erb
  managing-store.html.md.erb
  managing-stores.html.md.erb
  using.html.md.erb
Labels: unscheduled

#72 Update release notes for 0.2.0 release
  release-notes.html.md.erb
Labels: unscheduled

#73 Final touches for installation docs
  installing.html.md.erb
Labels: scheduled

#68 Move managing projects section to tbs with projects section
  managing-projects.html.md.erb
  tbs-with-projects.html.md.erb
Labels: unscheduled
